finesauces_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('listings.urls', namespace='listings')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>', views.product_list, name='product_list_by_category'),
    path('<slug:category_slug>/<slug:product_slug>', views.product_detail, name='product_detail'),

]

listings/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100,unique=True)
    slug = models.SlugField(max_length=100,unique=True)

    class Meta:
        ordering = ('-name',)
        verbose_name_plural = 'categories'

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse(
            'listings:product_list_by_category',            
            args=[self.slug]
            )
    

class Product(models.Model):
    category = models.ForeignKey(
        Category, 
        related_name='products', 
        on_delete=models.CASCADE
        )
    name = models.CharField(max_length=100,unique=True)
    slug = models.SlugField(max_length=100,unique=True)
    image = models.ImageField(upload_to='products/')
    description = models.TextField()
    shu = models.CharField(max_length=10)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ('shu',)
    
    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse(
            'listings:product_detail',            
            args=[self.category.slug, self.slug]
            )

class Review(models.Model):
    product = models.ForeignKey(
        Product,
        related_name='reviews',
        on_delete=models.CASCADE
    )

    author = models.CharField(max_length=50)
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    text = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

listings/views.py
import re
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product, Review
from .form import ReviewForm

# Create your views here.

def product_list(request, category_slug=None):
    categories = Category.objects.all()
    requested_category = None
    products = Product.objects.all()    

    if category_slug:
        requested_category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=requested_category)

    return render(
        request,
        'product/list.html',
        {
            'categories':categories,
            'requested_category': requested_category,
            'products':products
        }
    )

def product_detail(request, category_slug, product_slug):
    category = get_object_or_404(Category, slug=category_slug)
    product = get_object_or_404(
        Product,
        category_id = category.id,
        slug = product_slug
    )

    if request.method == 'POST':
        review_form = ReviewForm(request.POST)

        if review_form.is_valid():
            cf = review_form.cleaned_data

            author_name = "Anonymous"
            Review.objects.create(
                product = product,
                author = author_name,
                rating = cf['rating'],
                text = cf['text']
            )
        return redirect(
            'listings:product_detail',
            category_slug=category_slug, product_slug=product_slug
        )

    else:
        review_form = ReviewForm()        

        return render(
            request,
            'product/detail.html',
            {            
                'product':product,
                'review_form': review_form
            }
        )

listings/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fontawesome/5.13.0/css/all.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito&display=swap">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"/>
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-danger fixed-top py-1"
    id="main-nav">
    <div class="container">
      <a href="{% url 'listings:product_list' %}" class="navbar-brand">
        <h3 class="font-weight-bold">finesauces</h3>
      </a>
    </div>
  </nav>
  <div class="container py-5">
  {% block content %}
  {% endblock content %}
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
    integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>
 <script src=" {% static 'js/scripts.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js">
</script>
</body>
</html>

listings/templates/product/detail.html
{% extends 'base.html' %}
{% block title %}{{ product.name }}{% endblock %}
{% block content %}
<div class="card shadow-custom border-0 col-lg-8 mx-auto">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <img src="{{ product.image.url }}" alt=""
        class="img-fluid rounded-0">
    </div>
    <div class="col-lg-6">
      <div class="top">
        <h2 class="mt-4 font-weight-bold text-grey">
          {{ product.name }}
        </h2>
         <div>
          <span class="font-weight-bold text-grey">
            Hotness:
          </span> {{ product.shu }} SHU
        </div>
        <div>
          <span class="font-weight-bold text-grey">
            Volume:
          </span> 100ml
        </div>
      </div>
      <div class="mt-3">
        {{ product.description }}
      </div>
      {% if product.available %}
        <div class="alert alert-success my-3 text-center">
          Available
        </div>
      {% else %}
        <div class="alert alert-danger my-3 text-center">
          Currently unavailable
        </div>
      {% endif %}
      <hr>
      <div class="review">
        <span class="font-weight-bold text-grey">
          Average rating: 4.5/5.0
        </span>
        <div class="mb-3 font-weight-bold">
            <a href="" class="text-warning" data-toggle="modal" data-target="#myModal" >
                Write review
              </a>
            </div>
          </div>
          <div class="mb-4">
            <form>
              <span class="input-group add-to-cart shadow-custom">
                <div class="input-group-prepend">
                  <span class="input-group-text
                    font-weight-bold px-3 btn btn-block price">
                    ${{ product.price }}
                  </span>
                 </div>
                <span id="minus" class="input-group-text button_minus px-4">
                  -
                </span>
                <input type="number" value="1" class="form-control
                  text-center px-3">
                <span id="plus" class="input-group-text button_plus px-4">
                  +
                </span>
                <div class="input-group-append">
                  <button class="btn btn-danger px-4 reduce_padding"
                    type="submit" data-toggle="tooltip"
                    data-placement="top" title="Add to cart">
                    <i class="fas fa-shopping-cart"></i>
                  </button>
                </div>
              </span>
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- MODAL -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Write your review</h5>
          <button class="close" data-dismiss="modal">×</button>
        </div>
        <form>
          <div class="modal-body">
             <div class="bg-grey">
              <div class="text-center pt-2">
                Rating:
                <div id="full-stars" class="d-inline text-center">
                  <div class="rating-group">
                    <label class="rating__label" for="id_rating_0">
                      <i class="rating__icon rating__icon--star fa fa-star">
                      </i>
                    </label>
                    <input class="rating__input" name="rating"
                      id="id_rating_0" value="1" type="radio" required>
                    <label class="rating__label" for="id_rating_1">
                      <i class="rating__icon rating__icon--star fa fa-star">
                      </i>
                    </label>
                    <input class="rating__input" name="rating"
                      id="id_rating_1" value="2" type="radio" required>
                    <label class="rating__label" for="id_rating_2">
                      <i class="rating__icon rating__icon--star fa fa-star">
                      </i>
                    </label>
                    <input class="rating__input" name="rating"
                      id="id_rating_2" value="3" type="radio" required>
                    <label class="rating__label" for="id_rating_3">
                      <i class="rating__icon rating__icon--star fa fa-star">
                      </i>
                    </label>
                    <input class="rating__input" name="rating"
                      id="id_rating_3" value="4" type="radio" required>
                    <label class="rating__label" for="id_rating_4">
                      <i class="rating__icon rating__icon--star fa fa-star">
                      </i>
                    </label>
                    <input class="rating__input" name="rating"
                      id="id_rating_4" value="5" type="radio" checked required>
                  </div>
                </div>
              </div>
               <hr class="m-0">
              <div class="input-field text-center p-2">
                <textarea cols="40" rows="6"
                  class="form-control shadow px-2">
                </textarea>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button class="btn btn-danger" type="submit">Confirm</button>
          </div>
        </form>
      </div>
    </div>
</div>
{% endblock content %}

listings/templates/product/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}finesauces{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-lg-3">
    <div class="card shadow-custom border-0">
      <h4 class="p-3 font-weight-bold text-grey">
        Categories
      </h4>
      <ul class="list-group border-0 categories_list">
        <li
            {% if not requested_category %}
                class="list-group-item border-0 p-0 selected"
            {% else %}
                class="list-group-item border-0 p-0 unselected"
            {% endif %}>
                <a href="{% url 'listings:product_list' %}"
                class="btn btn-block text-left">All</a>
        </li>
        {% for category in categories %}
            <li
                {% if category.slug == requested_category.slug %}
                    class="list-group-item border-0 p-0 selected"
                {% else %}
                    class="list-group-item border-0 p-0 unselected"
                {% endif %}>
                <a href="{{ category.get_absolute_url }}"
                    class="btn btn-block text-left">
                    {{ category.name }}
                </a>
            </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card shadow-custom border-0 mb-4">
      <div class="card-body text-center">
        <h2 class="font-weight-bold text-grey">
          {% if requested_category %}
            {{requested_category.name}}
          {% else %}
            Our products
          {% endif %}
        </h2>
        <div class="bottom_line"></div>
      </div>
    </div>
    <div class="row no-gutters">
    {% for product in products %}
      <div class="col-sm-6">
        <div class="card product">
          <div class="item">
            <div class="item-image">
              <img src="{{ product.image.url }}" alt=""
                class="img-fluid rounded-0">
            </div>
            <div class="item-text">
              <div class="item-text-wrap">
                <a href="{{ product.get_absolute_url }} " 
                  class="h2 text-white text-decoration-none">
                  {% comment %} <i class="fas fa-search-plus"></i> {% endcomment %}
                  <img src="{% static 'icons/clear.png' %}"/>
                </a>
              </div>
            </div>
            <div class="card-body text-center">
              {{ product.name }}
              <hr>
              <span>${{ product.price }}</span>
              <div>
                <i class="fas fa-fire"></i> {{ product.shu }} SHU
              </div>
            </div>
          </div>
         </div>
      </div>
    {% endfor %}
    </div>
  </div>
  <div class="col-lg-3"></div>
</div>
<hr>
{% endblock content %}